#!/bin/bash

# test the github distribution in a container

# build the base container

docker build -t webdatasettest-base - <<EOF
FROM ubuntu:19.10
ENV LC_ALL=C
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qqy update
RUN apt-get install -qqy git
RUN apt-get install -qqy python3
RUN apt-get install -qqy python3-pip
RUN apt-get install -qqy python3-venv
RUN apt-get install -qqy curl
WORKDIR /tmp
RUN python3 -m venv venv
RUN . venv/bin/activate; pip install --no-cache-dir pytest
RUN . venv/bin/activate; pip install --no-cache-dir torch==1.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
RUN . venv/bin/activate; pip install --no-cache-dir numpy
RUN . venv/bin/activate; pip install --no-cache-dir nbconvert
RUN . venv/bin/activate; pip install --no-cache-dir torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
EOF


case $1 in

local)
cat > Dockerfile <<EOF
FROM webdatasettest-base
ENV SHELL=/bin/bash
COPY . /tmp/webdataset
WORKDIR /tmp/webdataset
RUN ls -l
RUN ln -s /tmp/venv .
RUN . venv/bin/activate; pip install --no-cache-dir pytest
RUN . venv/bin/activate; pip install --no-cache-dir -r requirements.txt
RUN . venv/bin/activate; python3 -m pytest
EOF
docker build -t webdatasettest .
rm -f Dockerfile
;;

# run the test as a second stage build without caching

git)
docker build -t webdatasettest --no-cache - <<EOF
FROM webdatasettest-base
ENV SHELL=/bin/bash
RUN git clone https://git@github.com/tmbdev/webdataset.git /tmp/webdataset
WORKDIR /tmp/webdataset
RUN ln -s /tmp/venv .
RUN . venv/bin/activate; pip install --no-cache-dir pytest
RUN . venv/bin/activate; pip install --no-cache-dir -r requirements.txt
RUN . venv/bin/activate; python3 -m pytest
EOF
;;

package)
cd dist || exit 1
cat > Dockerfile <<EOF
FROM webdatasettest-base
ENV SHELL=/bin/bash
RUN git clone https://git@github.com/tmbdev/webdataset.git /tmp/webdataset
RUN mkdir /tmp/work
RUN cp -av /tmp/webdataset/test* /tmp/work/.
WORKDIR /tmp/work
RUN ln -s /tmp/venv .
RUN . venv/bin/activate; pip install --no-cache-dir pytest
#RUN . venv/bin/activate; pip install --no-cache-dir webdataset
#RUN . venv/bin/activate; pip install https://tmb-testreleases.storage.googleapis.com/webdataset-latest-py3-none-any.whl
ADD webdataset-*.whl /tmp
RUN . venv/bin/activate; pip install --no-cache-dir /tmp/webdataset-*-py3-none-any.whl
RUN . venv/bin/activate; python3 -m pytest
EOF
docker build -t webdatasettest .
rm -f Dockerfile
;;

pip)
docker build -t webdatasettest --no-cache - <<EOF
FROM webdatasettest-base
ENV SHELL=/bin/bash
RUN git clone https://git@github.com/tmbdev/webdataset.git /tmp/webdataset
WORKDIR /tmp/webdataset
RUN rm -rf webdataset
RUN ln -s /tmp/venv .
RUN . venv/bin/activate; pip install --no-cache-dir pytest
RUN . venv/bin/activate; pip install --no-cache-dir webdataset
RUN . venv/bin/activate; python3 -m pytest
EOF
;;

*)
echo $1: must specify either pip or git
exit 1
;;

esac
