#!/bin/bash

# test the github distribution in a container

# build the base container

docker build -t webdatasettest-base - <<EOF
FROM ubuntu:19.10
ENV LC_ALL=C
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qqy update
RUN apt-get install -qqy git
RUN apt-get install -qqy python3
RUN apt-get install -qqy python3-pip
RUN apt-get install -qqy python3-venv
RUN apt-get install -qqy curl
WORKDIR /tmp
RUN python3 -m venv venv
RUN . venv/bin/activate; pip install --no-cache-dir pytest
RUN . venv/bin/activate; pip install --no-cache-dir torch==1.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
RUN . venv/bin/activate; pip install --no-cache-dir numpy
RUN . venv/bin/activate; pip install --no-cache-dir nbconvert
RUN . venv/bin/activate; pip install --no-cache-dir torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
EOF


case $1 in

local)

cat > Dockerfile <<EOF
FROM webdatasettest-base
ENV SHELL=/bin/bash
COPY . /tmp/webdataset
WORKDIR /tmp/webdataset
RUN ls -l
RUN ln -s /tmp/venv .
RUN . venv/bin/activate; pip install --no-cache-dir pytest
RUN . venv/bin/activate; pip install --no-cache-dir -r requirements.txt
RUN . venv/bin/activate; python3 -m pytest
EOF

docker build -t webdatasettest .

rm -f Dockerfile
;;

# run the test as a second stage build without caching

git)

docker build -t webdatasettest --no-cache - <<EOF
FROM webdatasettest-base
ENV SHELL=/bin/bash
RUN git clone https://git@github.com/tmbdev/webdataset.git /tmp/webdataset
WORKDIR /tmp/webdataset
RUN ln -s /tmp/venv .
RUN . venv/bin/activate; pip install --no-cache-dir pytest
RUN . venv/bin/activate; pip install --no-cache-dir -r requirements.txt
RUN . venv/bin/activate; python3 -m pytest
EOF
;;

# run the test as a second stage build without caching

pip)

docker build -t webdatasettest --no-cache - <<EOF
FROM webdatasettest-base
ENV SHELL=/bin/bash

RUN pip3 install webdataset

# we clone this just to get the tests

RUN git clone https://git@github.com/tmbdev/webdataset.git /tmp/webdataset
WORKDIR /tmp/webdataset

# we need to run the tests in the current directory
# but we want to make sure that we are using the globally
# installed libraries, so we move the subdirectory out of the way

RUN mv webdataset use-installed-webdataset

# note that for commands, this will test ./command, not /usr/local/bin/command

RUN python3 -m pytest
EOF
;;

*)
echo $1: must specify either pip or git
exit 1
;;

esac
