from . import dataset as dataset
from typing import Any

class TotalSize:
    count: int = ...
    total: int = ...
    def __init__(self) -> None: ...
    def __call__(self, sample: Any): ...

def main(args: Any) -> None: ...
