from .mock import IterableDataset as IterableDataset
from typing import Any, Optional

def get_uuid(data: Any): ...

class DBCache(IterableDataset):
    dbname: Any = ...
    source: Any = ...
    verbose: Any = ...
    db: Any = ...
    shuffle: Any = ...
    total: Any = ...
    size: Any = ...
    def __init__(self, dbname: Any, size: Any, source: Optional[Any] = ..., shuffle: bool = ..., verbose: bool = ...) -> None: ...
    def source_(self, source: Any): ...
    def __call__(self, source: Any): ...
    def getmeta(self, key: Any): ...
    def setmeta(self, key: Any, value: Any) -> None: ...
    def __len__(self): ...
    def dbiter(self) -> None: ...
    def key_exists(self, key: Any): ...
    def __iter__(self) -> Any: ...
