from . import autodecode as autodecode, iterators as iterators, tariterators as tariterators
from .dataset import WebDataset as WebDataset, default_cache_dir as default_cache_dir, default_cache_name as default_cache_name, default_cache_size as default_cache_size, default_cache_verbose as default_cache_verbose, split_by_worker as split_by_worker
from .mock import IterableDataset as IterableDataset
from .utils import reraise_exception as reraise_exception
from typing import Any

class Dataset(IterableDataset):
    def __init__(self, urls: Any, *, length: bool = ..., splitter: Any = ..., handler: Any = ..., shuffle: bool = ..., cache_dir: Any = ..., cache_size: Any = ..., cache_name: Any = ..., cache_verbose: Any = ...) -> None: ...
    def __getattr__(self, name: Any): ...
    def __iter__(self) -> Any: ...
    def __len__(self): ...
