import io
from typing import Any

def guess_shard(path: Any): ...
def shard_uuid(path: Any): ...

class CacheStream(io.RawIOBase):
    verbose: Any = ...
    stream: Any = ...
    fname: Any = ...
    tempname: Any = ...
    cache: Any = ...
    def __init__(self, fname: Any, stream: Any, verbose: bool = ...) -> None: ...
    def close(self, complete: bool = ...) -> None: ...
    last: Any = ...
    def read(self, n: Any): ...
    def readinto(self, b: Any): ...

def cache_shards(
    urls: Any,
    cache_dir: str = ...,
    cache_size: float = ...,
    cache_name: Any = ...,
    verbose: bool = ...,
) -> None: ...
