from . import gopen as gopen
from .utils import reraise_exception as reraise_exception
from typing import Any, Optional

trace: bool
meta_prefix: str
meta_suffix: str

def base_plus_ext(path: Any): ...
def valid_sample(sample: Any): ...
def shardlist(urls: Any, *, shuffle: bool = ...) -> None: ...
def url_opener(data: Any, handler: Any = ..., **kw: Any) -> None: ...
def tar_file_iterator(fileobj: Any, skip_meta: str = ..., handler: Any = ...) -> None: ...
def tar_file_expander(data: Any, handler: Any = ...) -> None: ...
def group_by_keys(data: Any, keys: Any = ..., lcase: bool = ..., suffixes: Optional[Any] = ..., handler: Optional[Any] = ...) -> None: ...
