from typing import Any, Optional

def reraise_exception(exn: Any) -> None: ...
def ignore_and_continue(exn: Any): ...
def warn_and_continue(exn: Any): ...
def ignore_and_stop(exn: Any): ...
def warn_and_stop(exn: Any): ...
def identity(x: Any): ...
def safe_eval(s: Any, expr: str = ...): ...
def lookup_sym(sym: Any, modules: Any): ...
def repeatedly0(loader: Any, nepochs: int = ..., nbatches: int = ...) -> None: ...
def guess_batchsize(batch: Any): ...
def repeatedly(source: Any, nepochs: Optional[Any] = ..., nbatches: Optional[Any] = ..., nsamples: Optional[Any] = ..., batchsize: Any = ...) -> None: ...
