from typing import NoReturn, TypeVar

E = TypeVar('E', bound=Exception)

def reraise_exception(exn: E) -> NoReturn: ...
def ignore_and_continue(exn: E) -> bool: ...
def warn_and_continue(exn: E) -> bool: ...
def ignore_and_stop(exn: E) -> bool: ...
def warn_and_stop(exn: E) -> bool: ...
